version: '3.7'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', 'localhost', '--password=mysql']
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 60s

volumes:
  mysql-store:
