parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  es6: true
plugins:
  - react
extends:
  - google
  - plugin:react/recommended
  - plugin:prettier/recommended
settings:
  react:
    version: 16.5.1
rules:
  react/jsx-uses-vars:
    - 1
  prettier/prettier:
    - error
    -
      singleQuote: true
      semi: false
      trailingComma: es5

