name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '23.0.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Restore plt files
      uses: actions/cache@v2
      with:
        path: priv/plts
        key: ${{ runner.os }}-elixir-1.10.3-otp-23.0.3-plts
        restore-keys: ${{ runner.os }}-
    - name: Install dependencies
      run: mix deps.get
    - name: Prepare Database
      run: sudo systemctl start mysql.service
    - name: Check code format
      run: mix format --check-formatted
    - name: Run Lint
      run: mix credo
    - name: Run dialyzer
      run: mix dialyzer
    - name: Run tests
      run: mix test
